### ISSUE TITLE
numbers for countries seem to have doubled

### ISSUE THREAD

**Issue by timholz** [apfeuti/covid19-rest#5]
Hi-today i noticed a significant jump for confirmed and deaths.
Spain reports:
ncumul_conf: **458’231** and 
ncumul_deceased: **54’425**
Comparing with [jhu](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) I get for Spain:
ncumul_conf: **230.183** and 
ncumul_deceased:  **27.459**
This difference is huge. Can you please check this difference.
Thanks.

**Comment by timholz** [comment]
Figures unreliable. Plugin deleted.

**Comment by apfeuti** [comment]
Since 2020-05-14 the data is reported per area for Spain.
https://covid19-rest.herokuapp.com/api/jhu/v1/country/esp?date=2020-05-13
https://covid19-rest.herokuapp.com/api/jhu/v1/country/esp?date=2020-05-14

If this happens, then the total-records without a date-parameter is no longer reliable.
I recommend to always use the data-parameter, then you have a clear view to that given date.

**Comment by timholz** [comment]
thanks for the update
