### ISSUE TITLE
Url reports application error

### ISSUE THREAD

**Issue by timholz** [apfeuti/covid19-rest#6]
Hi

This [example](https://covid19-rest.herokuapp.com/api/openzh/v1/all?skipRecords=true) reports;

**Application error**

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

all urls are affected.
are the still valid?
regards
theo

**Comment by RlnmnsRimanslim** [comment]
Hi!

Seems to affect the whole application. Would be very nice if you could fix the problem.

Rlnmns

**Comment by apfeuti** [comment]
Will care about after when I'm back from my holidays (early August)

RlnmnsRimanslim <notifications@github.com> schrieb am Mi., 22. Juli 2020,
10:33:

**Comment by apfeuti** [comment]
Data from openZH  (api/openZH/v1) is available again.

But I had to disable the data from Johns Hopkins University (api/jhu/v1) because my free Heroku-Server runs out of memory. If you need this API, run this API-Server on your own infrastructure. Any Laptop with approx 1.5 GB free memory is fine. Follow this guideline: https://github.com/apfeuti/covid19-rest#Developers
